name: CI/CD + Gmail + Slack Notifications

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: rushi-tech-site
      IMAGE_TAG: latest
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      REMOTE_USER: ec2-user
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

    - name: Push Docker Image
      run: |
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG

    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.REMOTE_HOST }}
        username: ${{ env.REMOTE_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker stop rushi-container || true
          docker rm rushi-container || true
          docker pull $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
          docker run -d -p 80:80 --name rushi-container $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG


    - name: Gmail Email Notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ env.GMAIL_USER }}
        password: ${{ env.GMAIL_APP_PASSWORD }}
        subject: GitHub Actions Build ${{ job.status }} - ${{ github.repository }}
        to: ${{ env.EMAIL_TO }}
        from: Rushi CI <${{ env.GMAIL_USER }}>
        content_type: text/html
        body: |
          <p><strong>Workflow:</strong> ${{ github.workflow }}</p>
          <p><strong>Status:</strong> ${{ job.status }}</p>
          <p><strong>Branch:</strong> ${{ github.ref }}</p>
          <p><strong>Commit:</strong> ${{ github.sha }}</p>
          <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Logs</a></p>
